include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = iOS26SpooferPrefs

iOS26SpooferPrefs_FILES = I26RootListController.m
iOS26SpooferPrefs_FRAMEWORKS = UIKit
iOS26SpooferPrefs_PRIVATE_FRAMEWORKS = Preferences
iOS26SpooferPrefs_INSTALL_PATH = /Library/PreferenceBundles
iOS26SpooferPrefs_CFLAGS = -fobjc-arc
iOS26SpooferPrefs_RESOURCE_DIRS = Resources

include $(THEOS_MAKE_PATH)/bundle.mk
